patrol_points:
  - x: 1.0
    y: 1.0
  - x: 2.0
    y: 2.0
  - x: 3.0
    y: 1.0
  - x: 2.0
    y: 0.0

supply_point:
  x: 0.0
  y: 0.0

blood_threshold: 50

blood: 500

ammo_full: 100
ammo_threshold: 20
ammo: 100

enemy_lost_timeout_sec: 15.0